### ISSUE TITLE
Fix confusing error message in DataServlet::doGet

### ISSUE THREAD

**Issue by KoopaKing** [cli1903/step#20]
When `DataServlet::doGet` receives a request with an invalid `num-comments` parameter it returns the error message: `"Please enter an integer between 0 and 15."`

That error message is not informative for what happened and seems to be directed to UI users even though it is being returned by the server. It does not specify which request parameter should be between 0 and 15 but assumes that a form is being filled out where the user will know where they were entering a number.

**Comment by cli1903** [comment]
issue was resolved
